language: go
arch:
  - amd64
  - arm64
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

install: |
  mkdir -p $HOME/gopath/src/code.cloudfoundry.org/log-cache-cli
  rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/code.cloudfoundry.org/log-cache-cli/
  export TRAVIS_BUILD_DIR=$GOPATH/src/code.cloudfoundry.org/log-cache-cli
  go get -t -d -v code.cloudfoundry.org/log-cache-cli/...

script: go test code.cloudfoundry.org/log-cache-cli/... --race

matrix:
  allow_failures:
  - go: master
  exclude:
  - arch: arm64
    go: master
